# Navigation Links

main:
  - name: Bio
    url: /
    weight: 10
  - name: Research
    url: /#research
    weight: 11
  - name: Publications
    url: /#papers
    weight: 12
  - name: Projects
    url: /#projects
    weight: 13
  - name: CV
    url: /experience/
    weight: 14
  - name: News
    url: /#news
    weight: 15
  - name: Contact
    url: /#contact
    weight: 16
